name: AttendTap
description: "personal attendance management app"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.8
  sqflite: ^2.2.0
  path: ^1.8.0
  intl: ^0.19.0
  flutter_datetime_picker_plus: ^2.2.0
  table_calendar: ^3.1.2
  flutter_localizations:
    sdk: flutter
  month_picker_dialog: ^5.1.3
  shared_preferences: ^2.3.3
  package_info_plus: ^8.1.1
  google_mobile_ads: ^5.2.0
  url_launcher: ^6.3.1
  app_tracking_transparency: ^2.0.6
  async_preferences: ^1.0.1
  restart_app: ^1.3.2
  flutter_dotenv: ^5.2.1
  flutter_native_splash: ^2.0.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
  fonts:
    - family: Gothic
      fonts:
        - asset: assets/fonts/HiraginoGothic.ttc

    - family: Mincho
      fonts:
        - asset: assets/fonts/HiraginoMincho.ttc

    - family: Anzu
      fonts:
        - asset: assets/fonts/APJapanesefont.ttf

    - family: Annai
      fonts:
        - asset: assets/fonts/AnnaiMN.ttf

dev_dependencies:
  flutter_launcher_icons: ^0.14.2
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios : true
  adaptive_icon_background: "assets/icons/background.png"
  adaptive_icon_foreground: "assets/icons/foreground.png"
  image_path: "assets/icons/icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/AttendTapSplash.png
  android: true
  ios: true
  android_12:
    color: "#ffffff"
    image: assets/images/AttendTapSplash.png
